# Generated by Django 5.2.13 on 2026-05-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время записи'),
        ),
    ]
